### ISSUE TITLE
🐛 Fix type error for peer dependency when compiling typescript

### ISSUE THREAD

**Issue by ncn-ssw** [tinacms/tinacms#4578]
CC : @wicksipedia , @JackDevAU 

Hi Team, 

As per conversation with Jack P and Wicksy, the current build pipeline in TinaCMS is broken, preventing any PRs from being merged. After investigation, this is likely due to a new release of one of the transitive packages used in TinaCMS [radix](https://www.radix-ui.com/primitives/docs/overview/releases) and typescript compiler start throwing error

![Image](https://github.com/tinacms/tinacms/assets/87377903/19c7fd7c-0ed9-4687-aa83-66913eb6da25)
**Figure : Error in build pipeline when running pnpm tsc**

The solution was to upgrade the TypeScript version in the packages causing the error. However, this requires refactoring and testing each peer dependency to ensure compatibility with the new TypeScript version ⚠️.

**Tasks**
- [x] Upgrade typescript version to solve the build error in CI 
- [x] Fix error and refactor broken code after typescript upgrade 
- [ ] Clean up 

Here are some reference for solution:

Some improvement made from Wicksy (standardize pnpm version and etc) - https://github.com/tinacms/tinacms/pull/4575
Possible solution (the last commit showing update typescript version will fix the issue) - https://github.com/tinacms/tinacms/pull/4574

**Comment by JackDevAU** [comment]
Update: 

Using [Knip](https://github.com/webpro-nl/knip) I've started going through and weeding out package dependancies that aren't being used. I think there may need to be a larger task down the line to audit tinacms and potentially re-architect some of the package scaffolding, clearing out the dead/unused code. 

PR: https://github.com/tinacms/tinacms/pull/4591

**Comment by JackDevAU** [comment]
✅ Done - Tested and deployed in version 1.6.5

**Comment by MihaiCGL** [comment]
TinaCMC version 1.6.5

I still get the same errors as above. I already tried a clean install

![image](https://github.com/tinacms/tinacms/assets/138451925/7a63361b-38c9-449e-862d-5cd6f349a232)

**Comment by wicksipedia** [comment]
Hey @MihaiCGL are you able to share more info (frameworks, versions, etc) in a separate issue?
I've seen some GitHub issues where this is type of thing is originating from vite and one of its plugins

**Comment by oliver-daniel** [comment]
I also encounter the `"use client" was ignored` issue in my automated Tina builds. It doesn't seem to cause any issues beyond visual noise, but i'd prefer not to see it if it can be helped.
