### ISSUE TITLE
TinaCMS CLI Setup Process Fails in Existing Astro Project

### ISSUE THREAD

**Issue by jan10** [tinacms/tinacms#4760]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

When attempting to install TinaCMS in an existing Astro project, the CLI setup process does not complete successfully.

## Expected Behavior:
The TinaCMS CLI setup process should complete without errors, successfully integrating TinaCMS into the existing Astro project.

## Actual Behavior:
The setup process fails with error messages, and TinaCMS is not integrated into the project.
![Image](https://github.com/user-attachments/assets/a386a4ca-5d5f-442f-89de-32b9e0c691e4)

## Additional Context:

- The Astro project was created using the official Astro CLI.
- The issue persists even after deleting node_modules and reinstalling dependencies.

### Reproduction

-

### Steps to reproduce

1. Create a new Astro project or use an existing one.
2. Follow the official TinaCMS [installation guide](https://tina.io/docs/frameworks/astro/).
3. Run the TinaCMS CLI setup command: `npx @tinacms/cli@latest init`
4. Observe the error messages and setup failure.

### System Info

  System:
    OS: macOS 15.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 9.63 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.3 - /opt/homebrew/bin/npm
    pnpm: 9.7.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 128.0.6613.114
    Chrome Canary: 130.0.6689.0
    Safari: 18.0

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by stfufane** [comment]
Hi there, can confirm same issue on Manjaro Linux with an Astro 4.15.4 existing project.

**Comment by JackDevAU** [comment]
Hey @jan10 & @stfufane 

This issue should now be resolved in version 1.6.3 (latest). Please try running `npx @tinacms/cli@latest init` again, and it should work as expected. Apologies for any inconvenience caused.

**Comment by jan10** [comment]
Hey @JackDevAU thanks! I can still reproduce the problem with 1.6.3:

![Image](https://github.com/user-attachments/assets/7ca96ebf-a7be-4bd5-8bac-2d8d3eb79e40)

**Comment by stfufane** [comment]
Hi there, sorry for the late testing. Just tried it and I got the same messages than @jan10  with the 1.6.3 version. Sorry :(

**Comment by Mad-Kat** [comment]
Could it be the same problem as #4710? Downgrading the node version solved the issue for me

**Comment by JackDevAU** [comment]
Hey All, 

Sorry this took a little while - this has now been fixed in version `v2.2.5` of `tinacms` & `v1.6.5` of the `@tinacms/cli `. 

Please try again! 

Cheers, 

The Tina Team 🦙
