### ISSUE TITLE
Rich text editor - Multiple line breaks issue

### ISSUE THREAD

**Issue by PothieuG** [tinacms/tinacms#5322]
The rich text editor is awesome, unfortunatly the multiple line breaks in it is not reflecting on the UI.  
A workaround is to switch to markdown editor and use ```\``` as many time we want line-break but it is not user-friendly for a non-dev.

![Image](https://github.com/user-attachments/assets/e2ad3a8b-b0d2-43a1-a0e8-92b5dd4a684d)
**Figure: the multiple line breaks on rich text editor are not reflected on the ui**

**Comment by wicksipedia** [comment]
✅ Done - this is possible by pressing `shift+enter` in the editor (no update should be needed)

I've added some documentation to cover it off - https://github.com/tinacms/tina.io/pull/2670

**Comment by gustxyz** [comment]
@wicksipedia I am still seeing this issue in 3.6.1, seems like the shit+enter is inconsistent?

**Comment by gustxyz** [comment]
I'm seeing that embedded components seem un-effected (they render line breaks correctly), but as you can see in the screenshot, the line breaks are not being respected for other text.

I may create an embbed spacer component for my non-technical users in the interim, but would be ideal if there was a fix for this 

<img width="1327" height="571" alt="Image" src="https://github.com/user-attachments/assets/b0cdce15-7d41-4731-96b2-0354cbc18780" />

**Comment by wicksipedia** [comment]
Markdown is ideal when you have minimal presentational needs, or they can be modelled with components - so a spacer component would be the recommended approach if you want a reliable result. This comes from how acorn translates between markdown and AST. 

Alternatively, there are other ways to store the content as the AST directly e.g. json and slatejson

**Comment by gustxyz** [comment]
Interesting, is there any open issue related to this? (I found a similar issue you were involved that I commented on but it seems somewhat different).

I wouldn't mind taking a stab at it if you point me in the right direction! Seems like something that would be ideal UX.
