### ISSUE TITLE
Tina CMS Cloud Media Section Image Bug

### ISSUE THREAD

**Issue by rafay99-epic** [tinacms/tinacms#6019]
### Describe the issue that you're seeing. Any videos (eg. YouTube or Loom) or screenshots help!

So I just recently upgrade my tina CMS Version and I ran the build but when I opened the meda center in the Tina Cloud, I was getting this 

<img width="1512" height="982" alt="Image" src="https://github.com/user-attachments/assets/a3ecedfd-517c-425f-a806-8c5f396d0bb4" />

and this is happening for the last month, becase, I can not write or import any media into my blog post, Please can you check this out fro me or what might be the issue, 

So my site url is rafay99.com, I am using astro with Tina CMS and It was working perfectly, but all of the sudden things have statred to break down, why this is happen, any Idea? 

the github repo is https://github.com/rafay99-epic/Astro-Portfolio-Blog/

please when you have the time, fix this for, Now, I am down grading the Tina CMS Versison to fix this issue.

<img width="1512" height="982" alt="Image" src="https://github.com/user-attachments/assets/eb62f970-a17a-4720-9df5-277358c8eb1a" />

There are a few errors in the console; some are related to access tokens, but others may be something I don't understand. 

### Reproduction

https://github.com/rafay99-epic/Astro-Portfolio-Blog/

### System Info

```shell
This is live after the build, so I have no acess to the logs 

How every there are few errors in the console

which are stated in the above image
```

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by joshbermanssw** [comment]
Hi @rafay99-epic - this was addressed in the latest version of TinaCMS (v2.9.0). Find the changelog at https://tina.io/whats-new/tinacms. 

Let me know if you have any other issues with this :) 

Cheers

**Comment by rafay99-epic** [comment]
@joshbermanssw 

Thanks for helping me, out, I though this was not resolved, but thanks for point me in the correct direction. 

Thank You, 
Cheers.
